package com.example.biao.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.biao.greendaodemo.Uaer;

import com.example.biao.greendao.UaerDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig uaerDaoConfig;

    private final UaerDao uaerDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        uaerDaoConfig = daoConfigMap.get(UaerDao.class).clone();
        uaerDaoConfig.initIdentityScope(type);

        uaerDao = new UaerDao(uaerDaoConfig, this);

        registerDao(Uaer.class, uaerDao);
    }
    
    public void clear() {
        uaerDaoConfig.clearIdentityScope();
    }

    public UaerDao getUaerDao() {
        return uaerDao;
    }

}
